#!/bin/bash
set -e

export SCRIPTS=/usr/libexec/edgi
export EDGI_SYSTEM=/.base/edgi/system

reinit_debug()
{
    if [ "$EDGI_DEBUG" = "true" ]; then
        set -x
        return 0
    fi

    if [ -e /run/edgi/debug ]; then
        set -x
        return 0
    fi

    if [ -e /proc/cmdline ]; then
        for x in $(cat /proc/cmdline); do
            case $x in
                edgi.debug*)
                    export EDGI_DEBUG=true
                    mkdir -p /run/edgi
                    echo debug > /run/edgi/debug || true
                    ;;
            esac
        done
    fi

    if [ "$EDGI_DEBUG" = "true" ]; then
        set -x
    fi
}

setup_kernel()
{
    KERNEL=${EDGI_SYSTEM}/kernel/$(uname -r)/kernel.squashfs
    if [ ! -e ${KERNEL} ]; then
        return 0
    fi

    mkdir -p /run/edgi/kernel
    mount -t squashfs $KERNEL /run/edgi/kernel

    mount --bind /run/edgi/kernel/lib/modules /lib/modules
    mount --bind /run/edgi/kernel/lib/firmware /lib/firmware
    mount --bind /run/edgi/kernel/headers /usr/src

    umount /run/edgi/kernel
}

perr()
{
    echo "[ERROR]" "$@" 1>&2
}

pfatal()
{
    echo "[FATAL]" "$@" 1>&2
    exit 1
}

pinfo()
{
    echo " * " "$@"
}

cleanup()
{
    rm -rf /run/edgi
    unset SCRIPTS
    unset EDGI_SYSTEM
    if [ -n "$EDGI_MODE" ]; then
        mkdir -p /run/edgi
        echo "$EDGI_MODE" > /run/edgi/mode
    fi
    unset EDGI_MODE
}

reinit_debug
