#!/bin/bash

TARGET=/run/edgi/target

source /usr/lib/os-release

grow()
{
    parted $1 resizepart $2 100%
    partprobe $1
    sleep 2
    e2fsck -f $3
    resize2fs $3
}

setup_mounts()
{
    mkdir -p $TARGET
    mount -L EDGI_STATE $TARGET

    if [ -e $TARGET/edgi/system/growpart ]; then
        read DEV NUM < $TARGET/edgi/system/growpart
        if [ ! -e "${DEV}${NUM}" ]; then
            # /dev/sda2 => /dev/sda2
            # /dev/nvme0n1p2 => /dev/nvme0n1p2
            PART=$(blkid -L EDGI_STATE)

            # /dev/sda2 => /dev/sda
            # /dev/nvme0n1p2 => /dev/nvme0n1
            DEV=$(echo "$PART" | sed -r 's/((\d+)p)?\d+$/\2/')

            # /dev/sda2 => 2
            # /dev/nvme0n1p2 => 2
            NUM=$(echo "$PART" | sed 's!.*[^0-9]!!')
        fi
        if [ -e "${PART:=${DEV}${NUM}}" ]; then
            umount $TARGET
            grow $DEV $NUM $PART || true
            mount -L EDGI_STATE $TARGET
        fi
        rm -f $TARGET/edgi/system/growpart
    fi
}

setup_kernel_squashfs()
{
    KER_SRC="/.base/edgi/system/kernel/$(uname -r)/kernel.squashfs"
    KER_DEST="$TARGET/edgi/system/kernel/$(uname -r)/kernel.squashfs"
    if [ -e $KER_SRC ] && [ ! -e $KER_DEST ]; then
        mkdir -p $(dirname ${KER_DEST})
        cp -r $KER_SRC $KER_DEST
    fi
}

setup_edgi()
{
    if [ -e $TARGET/edgi/system/edgi/current/edgi ]; then
        return 0
    fi

    EDGI_SRC=/.base/edgi/system/edgi/current/edgi
    EDGI_FILE=$TARGET/edgi/system/edgi/${VERSION_ID}/edgi

    if [ ! -e ${EDGI_SRC} ]; then
        return 0
    fi

    if [ ! -e ${EDGI_FILE} ]; then
        mkdir -p $(dirname ${EDGI_FILE}.tmp)
        cp -f ${EDGI_SRC} ${EDGI_FILE}.tmp
        mv -f ${EDGI_FILE}.tmp ${EDGI_FILE}
    fi

    ln -sf ${VERSION_ID} $TARGET/edgi/system/edgi/current
}

setup_init()
{
    if [ -e $TARGET/sbin/init ]; then
        return 0
    fi

    mkdir -p $TARGET/sbin
    ln -sf ../edgi/system/edgi/current/edgi $TARGET/sbin/init
}

setup_k3s()
{
    if [ -e $TARGET/edgi/system/k3s/current/k3s ]; then
        return 0
    fi

    for i in $(ls -drt $TARGET/edgi/system/k3s/*); do
        if [ ! -L "$i" ]; then
            LATEST=$i
            break
        fi
    done

    if [ -e "${LATEST}" ]; then
        ln -sf $(basename "${LATEST}") $TARGET/edgi/system/k3s/current
        return 0
    fi
}

takeover()
{
    if [ ! -e edgi/system/takeover ]; then
        return 0
    fi

    touch edgi/system/factory-reset

    if [ -L sbin ]; then
      rm -f sbin
    fi

    for i in *; do
        case $i in
            boot|edgi|sbin)
                ;;
            *)
                rm -rf $i
        esac
    done
    for i in sbin/*; do
        case $i in
            sbin/init|sbin/k3s|sbin/edgi)
                ;;
            *)
                rm -rf "$i"
        esac
    done

    rm -rf boot/[^g]*
    rm -f edgi/system/takeover
    rm -rf edgi/data
    sync
    
    if [ -e edgi/system/poweroff ]; then
        rm -f edgi/system/poweroff
        sync
        poweroff -f
    else
        reboot -f
    fi
}

setup_mounts
setup_edgi
setup_kernel_squashfs
setup_init
setup_k3s

cd $TARGET

takeover || true

if [ -e edgi/system/factory-reset ] || [ -e edgi/system/ephemeral ]; then
    rm -rf edgi/data edgi/system/factory-reset
fi

losetup -d /dev/loop0 || true
mount --make-rprivate /
mkdir -p .root
pivot_root . .root
EDGI_MODE=local exec /sbin/init
