#!/bin/bash

setup_ssh()
{
    if [ ! -e /var/lib/cmd/edgi/ssh ]; then
        mkdir -p /var/lib/cmd/edgi
        cp -rf /etc/ssh /var/lib/cmd/edgi/ssh
    fi
    rm -rf /etc/ssh
    ln -s /var/lib/cmd/edgi/ssh /etc/ssh
}

setup_edgi_node()
{
    mkdir -p /etc/edgi
    mkdir -p /var/lib/cmd/edgi/node
    ln -s /var/lib/cmd/edgi/node /etc/edgi/
}

setup_ssh
setup_edgi_node
